namespace: kube-prometheus-stack

helmCharts:
- name: kube-prometheus-stack
  includeCRDs: true
  releaseName: kube-prometheus-stack
  version: 55.6.0
  repo:  https://prometheus-community.github.io/helm-charts