---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-service
  name: backend-service
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - image: docker.io/roelvandegrint/backend-service:0.3.0
          name: backend-service
          env:
            - name: OTEL_ENDPOINT
              value: http://grafana-alloy.grafana-alloy.svc.cluster.local:4317/
