---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-api
  name: web-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
        - image: docker.io/roelvandegrint/web-api:0.1.0
          name: web-api
          env:
            - name: OTEL_ENDPOINT
              value: http://grafana-alloy.grafana-alloy.svc.cluster.local:4317/
            - name: BACKEND_API_URI
              value: http://backend-service:8080
