apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo-domain-cert-staging
  namespace: istio-system
spec:
  secretName: bookinfo-domain-cert-staging
  # duration: 2160h # 90d
  # renewBefore: 360h # 15d
  # isCA: false
  # privateKey:
    # algorithm: RSA
    # encoding: PKCS1
    # size: 2048
  usages:
    - server auth
  dnsNames:
    - "bookinfo.roelvandegrint.com"
  issuerRef:
    name: letsencrypt-staging-http
    kind: Issuer
    group: cert-manager.io