apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - path: .
      repoURL: oci://ghcr.io/immich-app/immich-charts/immich
      targetRevision: v1.21.1
      helm:
        valueFiles:
          - $values/immich/values.yaml

    - repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
      targetRevision: add-immich
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: immich

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
