apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  external_services:
    prometheus:
      url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    grafana:
      in_cluster_url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
    tracing:
      in_cluster_url: http://simplest-query.observability.svc.cluster.local:16685
