apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  sources:
    - repoURL: ghcr.io/akuity/kargo-charts
      chart: kargo
      targetRevision: 1.10.4
      helm:
        valueFiles:
          - $values/kargo/helm/values.yaml

    - repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
      targetRevision: update_argocd_and_kargo_domains
      ref: values

    - repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
      targetRevision: update_argocd_and_kargo_domains
      path: kargo/kustomize/overlays/k3s

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: kargo-api # Or other Kargo secret creating a diff
      jsonPointers:
      - /data      

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
