apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.5/manifests/install.yaml
  # - argo-cd.application.yaml
  - argocd-internet.ingress.yaml
  - certmanager-letsencrypt-production.issuer.yaml

components: []

patches:
  - path: argocd-cm.configmap.yaml
  - path: argocd-cmd-params-cm.configmap.yaml
  - path: argocd-rbac-cm.configmap.yaml
