apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    - repoURL: https://github.com/argoproj/argo-workflows/releases/download/v4.1.4/install.yaml
      targetRevision: v4.1.4
      path: argo-workflows/manifests/cluster-install

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo

  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
