apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.17.1
      chart: cert-manager
      helm:
        valueFiles:
          - $values/cert-manager/values.yaml
  
    - repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
      targetRevision: phase_out
      ref: values
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
