apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    - path: .
      repoURL: oci://quay.io/jetstack/charts/cert-manager
      targetRevision: v1.20.2
      helm:
        valueFiles:
          - $values/cert-manager/values.yaml
  
    - repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
      targetRevision: upgrade-certmanager
      ref: values
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  
  syncPolicy:
    automated: 
      enabled: false
      prune: true
      selfHeal: false
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
