apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: dex
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.dexidp.io
      chart: dex
      targetRevision: 0.24.1
      helm:
        valueFiles:
          - $values/dex/values.yaml

    - repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
      targetRevision: dex
      ref: values

    - repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
      targetRevision: dex
      path: dex/kustomize

  # ignoreDifferences:
  #   - group: ""
  #     kind: Secret
  #     name: kargo-api # Or other Kargo secret creating a diff
  #     jsonPointers:
  #       - /data

  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
