apiVersion: v1
kind: Secret
metadata:
  name: test-repository-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:roelvandegrint/test.git
  name: GitHub SSH
