apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: whoami
  annotations:
    cert-manager.io/issuer: "le-example-http"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  tls:
    - hosts:
        - whoami.roelvandegrint.com
      secretName: tls-whoami-ingress-http
  rules:
    - host: whoami.roelvandegrint.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
