apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: whoami
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host('whoami.roelvandegrint.com')
      priority: 10
      services:
        - kind: Service
          name: whoami
          namespace: whoami
          port: 80
