apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-infrastructure
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"] 
  generators:
  - git:
      repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
      revision: HEAD
      directories:
      - path: kustomize/argocd-additions
      # - path: kustomize/kube-prometheus-stack-additions
      #   exclude: true
      # - path: kustomize/kubernetes-dashboard
        # exclude: true
      # - path: kustomize/traefik
        # exclude: true
      # - path: kustomize/keycloak
        # exclude: true
  template:
    metadata:
      name: '{{ .path.basename }}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
