apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-additions
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
    targetRevision: HEAD
    path: kustomize/cert-manager-kustomization
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
