apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/roelvandegrint/k3s.infrastructure
    targetRevision: main
    path: applications/argo-cd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
