apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 62.3.1
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/kube-prometheus-stack/values.yaml

    - repoURL: https://github.com/roelvandegrint/k3s.infrastructure.git
      targetRevision: kube-prometheus-stack
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
