apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-operator/kube-prometheus
    targetRevision: release-0.13
    path: manifests
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
