---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-jsonnet
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # annotations:
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        libs:
          - vendor
      recurse: true
    path: .
    repoURL: https://github.com/roelvandegrint/k3s.kube-prometheus.git
    targetRevision: HEAD
  # syncPolicy:
  #   automated: {}
---