apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/roelvandegrint/k3s.infrastructure
    targetRevision: nginx
    path: nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: default
