replicas: 1

prometheus:
  ingress:
    enabled: true

    hosts:
      - prometheus.k3s

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

    serviceMonitorNamespaceSelector: {}

    serviceMonitorSelector: {}

grafana:
  ingress:
    enabled: true

    hosts:
      - grafana.k3s
