replicas: 1

prometheus:
  ingress:
    enabled: true

    hosts:
      - prometheus.k3s

  prometheusSpec:
    serviceMonitorSelector: {}

    serviceMonitorNamespaceSelector:
      matchLabels:
        prometheus: cluster-monitoring

grafana:
  ingress:
    enabled: true

    hosts:
      - grafana.k3s
