replicas: 1

prometheus:
  ingress:
    enabled: true

    hosts:
      - prometheus.k3s

  prometheusSpec:
    serviceMonitorNamespaceSelector: {}

grafana:
  ingress:
    enabled: true

    hosts:
      - grafana.k3s
