replicas: 1

alertmanager:
  ## Alertmanager configuration directives
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
  ##
  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
      - target_matchers:
          - 'alertname = InfoInhibitor'
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - receiver: heartbeats
        matchers:
          - alertname = "Watchdog"
    receivers:
    - name: 'null'
    - name: heartbeats
      webhook_configs:
      - url: https://uptime.betterstack.com/api/v1/heartbeat/8CNpZaBrHRWFxu8TxJEXVq7K
        send_resolved: true
    templates:
    - '/etc/alertmanager/config/*.tmpl'

prometheus:
  ingress:
    enabled: true

    hosts:
      - prometheus.k3s

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

    serviceMonitorNamespaceSelector: {}

    serviceMonitorSelector: {}

grafana:
  ingress:
    enabled: true

    hosts:
      - grafana.k3s
